
POST http://127.0.0.1:8000/api/pipelines/top5/init
Content-Type: application/json

{
  "script": "Hello, world!",
  "volume_adjustment": -25,
  "subtitle_color": "white",
  "subtitle_highlight_color": "#7710e2"
}